revert changes back

diff --git a/.github/workflows/server.yml b/.github/workflows/server.yml
--- a/.github/workflows/server.yml
+++ b/.github/workflows/server.yml
@@ -38,12 +38,16 @@ jobs:
         working-directory: server
         run: |
           echo "eula=true" > eula.txt
+          mkfifo minecraft-console
 
           java -Xms1G -Xmx4G \
             -jar paper-1.12.2-1620.jar nogui \
+            < minecraft-console \
             > server.log 2>&1 &
 
           echo $! > server.pid
+
+          exec 3>minecraft-console
 
       - name: Wait for Minecraft server
         working-directory: server
@@ -98,6 +102,7 @@ jobs:
 
           if [ -z "$URL" ]; then
             echo "Cloudflare tunnel failed to start."
+            cat clourdflared.log
             exit 1
           fi
 
@@ -112,18 +117,43 @@ jobs:
 
           echo "CLOUDFLARED_PID=$CLOUDFLARED_PID" >> "$GITHUB_ENV"
 
-      - name: Monitor server
-        working-directory: server
+      - name: Save Minecraft server
+        if: always()
         run: |
-          echo "Server is running."
-          echo "Players can connect using the WSS address above."
-          echo ""
+          echo "Saving Minecraft server..."
+            rm -f server.zip
 
-          while kill -0 $(cat server.pid) 2>/dev/null; do
-            echo "----- Latest Minecraft log -----"
-            tail -n 10 server.log
-            echo "--------------------------------"
-            sleep 30
-          done
+          if [ -f server/server.pid ]; then
+            PID=$(cat server/server.pid)
+            zip -qr server.zip server/
 
-          echo "Minecraft server stopped."
+            if kill -0 "$PID" 2>/dev/null; then
+              echo "Sending stop command..."
+            echo "New server.zip created:"
+            ls -lh server.zip
+
+              echo "stop" > server/stop-command
+            echo ""
+            echo "=========================================="
+            echo "Uploading updated world..."
+            echo "=========================================="
+
+            TAG=$(gh release list \
+              --repo "$GITHUB_REPOSITORY" \
+              --limit 1 \
+              --json tagName \
+              --jq '.[0].tagName')
+
+            if [ -z "$TAG" ]; then
+              echo "ERROR: No GitHub Release found."
+              exit 1
+            fi
+
+              # Send the command through the server's stdin.
+              # Paper must receive the actual console command.
+              kill -TERM "$PID" 2>/dev/null || true
+            echo "Using release: $TAG"
+
+              sleep 10
+            fi
+          fi
